// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmUIMode(arg1) {
  return window['go']['desktop']['App']['ConfirmUIMode'](arg1);
}

export function GetConfig() {
  return window['go']['desktop']['App']['GetConfig']();
}

export function GetSnapshots() {
  return window['go']['desktop']['App']['GetSnapshots']();
}

export function GetUIMode() {
  return window['go']['desktop']['App']['GetUIMode']();
}

export function HidePopup() {
  return window['go']['desktop']['App']['HidePopup']();
}

export function OpenCodexHome() {
  return window['go']['desktop']['App']['OpenCodexHome']();
}

export function OpenDashboard(arg1) {
  return window['go']['desktop']['App']['OpenDashboard'](arg1);
}

export function OpenOfficialPanel() {
  return window['go']['desktop']['App']['OpenOfficialPanel']();
}

export function Quit() {
  return window['go']['desktop']['App']['Quit']();
}

export function Refresh() {
  return window['go']['desktop']['App']['Refresh']();
}

export function SaveConfig(arg1) {
  return window['go']['desktop']['App']['SaveConfig'](arg1);
}

export function ToggleMaximize() {
  return window['go']['desktop']['App']['ToggleMaximize']();
}
