// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {usage} from '../models';

export function ConfirmUIMode(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetSnapshots():Promise<Array<usage.Snapshot>>;

export function GetUIMode():Promise<string>;

export function HidePopup():Promise<void>;

export function OpenCodexHome():Promise<string>;

export function OpenDashboard(arg1:string):Promise<void>;

export function OpenOfficialPanel():Promise<void>;

export function Quit():Promise<void>;

export function Refresh():Promise<Array<usage.Snapshot>>;

export function SaveConfig(arg1:config.Config):Promise<config.Config>;

export function ToggleMaximize():Promise<void>;
